
AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for creating a VPC with an EC2 instance"

Parameters:
  VpcCidrBlock:
    Type: String
    Default: "10.0.0.0/16"
    Description: "CIDR block for the VPC"

Resources:
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: VpcCidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: "MyVPC"

  InternetGateway:
    Type: "AWS::EC2::InternetGateway"

  VPCGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId: VPC
      InternetGatewayId: InternetGateway

  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: VPC
      CidrBlock: "10.0.0.0/24"
      AvailabilityZone: 

  PublicSubnetRouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: VPC

  PublicSubnetRoute:
    Type: "AWS::EC2::Route"
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: PublicSubnetRouteTable
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: InternetGateway

  SubnetRouteTableAssociation:
    Type: "AWS::EC2::SubnetRouteTableAssociation"
    Properties:
      SubnetId: PublicSubnet
      RouteTableId: PublicSubnetRouteTable

  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group for EC2 instance"
      VpcId: VPC

  EC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-12345678"  #This should be replaced with the desired AMI ID
      InstanceType: "t2.micro"
      SecurityGroupIds:
        - SecurityGroup
      SubnetId: PublicSubnet

Outputs:
  VpcId:
    Description: "VPC ID"
    Value: VPC

  SubnetId:
    Description: "Public Subnet ID"
    Value: PublicSubnet

  InstanceId:
    Description: "EC2 Instance ID"
    Value: EC2Instance
